apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chevereto
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "" #leave blank if you only have localpath 
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "" #leave blank if you only have localpath
  resources:
    requests:
      storage: 5Gi